server:
  port: 9001

spring:
  application:
    name: service-zuul


  profiles:
    include: common_test

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/

  instance:
    instance-id: 网关服务-9003
    prefer-ip-address: true

zuul:
  routes:
    auth:
      path: /auth/**
      serviceId: service-auth
    general:
      path: /general/**
      serviceId: service-general
    play:
      path: /play/**
      serviceId: service-play